global:
  useDigest: false
  imagePullSecrets: []
    # - name: my-registry-secret
accessManager:
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/access-manager
      tag: v0.48.0
      digest: sha256:64f4ff2213c91b3f20117fbb5c8e879a5849628211620acabc77420fcbbc7aea
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
addonController:
  controller:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v0.48.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --agent-in-mgmt-cluster
      - --shard-key=
      - --v=5
      - --version=v0.48.0
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: docker.io/projectsveltos/addon-controller
      tag: v0.48.0
      digest: sha256:444d51fc5fefbc8cd769f250821e2e769f0c6f0280963cea4bb0f252b0a9a10a 
    resources:
      requests:
        memory: 512Mi
  driftDetectionManagerPatchConfigMap:
    name: drift-detection-config
    data: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  nodeSelector: {}
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
classifierManager:
  agentPatchConfigMap:
    name: sveltos-agent-config
    data: {}
  manager:
    args:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --shard-key=
      - --v=5
      - --version=v0.48.0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --agent-in-mgmt-cluster
      - --shard-key=
      - --v=5
      - --version=v0.48.0
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/classifier
      tag: v0.48.0
      digest: sha256:696e622c0d1542c8c759990b0d2a7f714dfd027f02501c64c255941bc7fabd40 
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
conversionWebhook:
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  sveltosWebhook:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/webhook-conversion
      tag: v0.48.0
      digest: sha256:4a6384773f892d143ea37b2cbf00aafc0c4848c540be082c7e4a9ebcf30ef802 
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  tolerations: []
driftDetectionManager:
  serviceAccount:
    annotations: {}
eventManager:
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v0.48.0
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/event-manager
      tag: v0.48.0
      digest: sha256:8f4fa918bedc22032e023c66e8ba308eb2f67049a9c0c9c3b9968bd7e3e23a62
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
hcManager:
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
      - --version=v0.48.0
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/healthcheck-manager
      tag: v0.48.0
      digest: sha256:c5944a31ce35b73ac967e5fbf34f586c20bd5d9ffe7dd35cfae57edc22e6ad62
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
registerMgmtCluster:
  serviceAccount:
    annotations: {}
registerMgmtClusterJob:
  backoffLimit: 4
  registerMgmtCluster:
    args:
      - --labels=
      - --service-account-token=false
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/register-mgmt-cluster
      tag: v0.48.0
      digest: sha256:4139a469de76b6a320ed9bc48b8f06e50c59a0fbd51306723e22ccd4a96b94c7
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 128Mi
scManager:
  manager:
    args:
      - --diagnostics-address=:8443
      - --shard-key=
      - --v=5
    extraArgs: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/sveltoscluster-manager
      tag: v0.48.0
      digest: sha256:e630107788a0f9dafcd7a361b06981edba420bb1f8a98f2f4eb8157124a1ae22
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 8443
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
  type: ClusterIP
shardController:
  extraEnv: []
  manager:
    args:
      - --diagnostics-address=:8443
      - --v=5
      - --report-mode=0
    extraArgs: {}
    argsAgentMgmtCluster:
      - --diagnostics-address=:8443
      - --report-mode=0
      - --agent-in-mgmt-cluster
      - --v=5
    extraArgsAgentMgmtCluster: {}
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: docker.io/projectsveltos/shard-controller
      tag: v0.48.0
      digest: sha256:da314f55323fd3abd07d61800cf3b035ac6c9c4f2981e277515d79ac7acfe6b6
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  tolerations: []
  serviceAccount:
    annotations: {}
sveltosAgentManager:
  serviceAccount:
    annotations: {}
prometheus:
  enabled: false
agent:
  managementCluster: false
telemetry:
  disabled: false
webhookService:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  type: ClusterIP
webhook:
  conversion: false
