apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-manager-rolebinding
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-manager
subjects:
- kind: ServiceAccount
  name: 'crd-manager'
  namespace: '{{ .Release.Namespace }}'