{{- if not (lookup "lib.projectsveltos.io/v1beta1" "Classifier" "" "default-classifier") }}
apiVersion: lib.projectsveltos.io/v1beta1
kind: Classifier
metadata:
  name: default-classifier
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  {{- with .Values.defaultClassifier.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": "hook-failed"
  {{- with .Values.defaultClassifier.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  classifierLabels:
  - key: sveltos-agent
    value: present
{{- end }}
