{{ if .Values.webhook.conversion }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sveltos-serving-cert
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "{{ .Release.Namespace }}.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "{{ .Release.Namespace }}.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: 'selfsigned-issuer'
  secretName: webhook-server-cert
{{ end }}
